- lib/plug/mailbox_preview.ex
- mix.exs
Since both Plug & Cowboy are marked as optional dependencies, they shouldn't be required to use. I tried using Swoosh on a project without them and couldn't compile it. This PR fixes it.
> Don't depend on Plug or Cowboy

- lib/swoosh/mailer.ex
- test/swoosh/mailer_test.exs
For some providers it's useful to be able to override the Mailer
config on a per-email basis. For instance, Mailgun requires you
to specify the domain you are sending from. If you are building
an app that's supporting several domains then you can use that
feature to pass the domain when making the call to deliver/2.
Fixes #46
> Support passing config as paramater to deliver/2

- lib/swoosh/adapters/smtp.ex
- test/swoosh/adapters/smtp_test.exs
Make SMTP adapter add additional headers from Email.headers
> Make SMTP adapter add additional headers from Email.headers

- README.md
https://github.com/swoosh/phoenix_swoosh/blob/master/lib/phoenix_swoosh.ex#L2
> Fixes README.md to match phoenix_swoosh docs

- lib/swoosh/adapters/smtp.ex
For SMTP use the "Sender" header, when it is set, as the "MAIL FROM" instead of the From address.
> Allow smtp "MAIL FROM" to be different to "From" header

- lib/swoosh/application.ex
> Display the actual port the mailbox preview server is exposed on.

- lib/swoosh/adapters/sendmail.ex
- lib/swoosh/adapters/smtp.ex
- test/swoosh/adapters/sendmail_test.exs
I haven't added any tests yet, just wanted to check what you thought first.
> Add Sendmail adapter

- .travis.yml
- mix.exs
- test/integration/adapters/mailgun_test.exs
- test/integration/adapters/postmark_test.exs
- test/integration/adapters/sendgrid_test.exs
- test/integration/adapters/smtp_test.exs
- test/swoosh/mailer_test.exs
- test/test_helper.exs
Most basic case, PRing to start discussion on where we put files, and see what opinions arise.
Also, defining a mailer seemed like overkill, but happy to do it if you disagree.
> Add basic integration test

- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/postmark.ex
- lib/swoosh/adapters/sendgrid.ex
- mix.exs
- mix.lock
This removes one dependency from the project, and I don't think it complicates it in any significant way.
> Drop dependency on httpoison, use hackney directly

- lib/swoosh/adapters/sendgrid.ex
- test/swoosh/adapters/sendgrid_test.exs
Pure JSON, custom variables, tests.
My first ever contribution to open-source! :)
> Sendgrid API v3

- lib/swoosh/adapters/smtp/helpers.ex
- test/swoosh/adapters/sendgrid_test.exs
- test/swoosh/email/smtp_test.exs
Fix missing Bcc for SMTP and Sendmail adapters
> Fix missing Bcc for SMTP and Sendmail adapters

- lib/mix/tasks/swoosh.mailbox.server.ex
- mix.exs
> Fixed compilator warnings for Elixir 1.4

- README.md
- lib/swoosh/adapters/sparkpost.ex
- test/swoosh/adapters/sparkpost_test.exs
> Add sparkpost

- lib/swoosh/adapters/sendgrid.ex
Tested with single and multiple attachments.
> Support attachments in Sendgrid adapter

- lib/swoosh/adapters/mailgun.ex
This is a follow up PR to #119
> Support attachments in Mailgun Adapter

- lib/swoosh/adapters/mandrill.ex
Docs ref: https://mandrillapp.com/api/docs/messages.JSON.html#method=send suggests
I don't use mandrill either, can't test...
> Support attachments in Mandrill adapter

- lib/swoosh/adapters/postmark.ex
I don't use Postmark so can't really test it through.
Docs ref: http://developer.postmarkapp.com/developer-send-api.html#attachments
> Support attachments in Postmark Adapter

- lib/swoosh/application.ex
If cowboy or plug aren't available, the preview server is no longer
started and instead, a warning is shown in the logs.
> Show a warning in the logs when failing to start the preview server

- lib/swoosh/email.ex
- test/swoosh/email_test.exs
I missed this one!
@stevedomin
> Allow adding attachments in Email.new

- README.md
Adding details on sending emails asynchronously. Touches on #136.
> Add async details to README.md.

- lib/swoosh/test_assertions.ex
- test/swoosh/test_assertions_test.exs
regarding discussions on slack
> Simplify email assertions

- .travis.yml
Elixir 1.5 is fully supported now
> Remove allowed failures

- lib/swoosh/mailer.ex
- test/swoosh/mailer_test.exs
@stevedomin @xadhoom
This should finish no.2 of https://github.com/swoosh/swoosh/issues/84#issuecomment-317634468
> Allow dynamic adapter

- mix.exs
- mix.lock
- test/swoosh/adapters/mailgun_test.exs
- test/swoosh/adapters/mandrill_test.exs
- test/swoosh/adapters/postmark_test.exs
- test/swoosh/adapters/sendgrid_test.exs
- test/swoosh/adapters/sparkpost_test.exs
@stevedomin 
looks like the bypass server is now killed after every test run. not sure if it's a change in Elixir 1.5 or Bypass.
> Upgrade bypass

- lib/swoosh/mailer.ex
> Add typespec to injected code

- lib/swoosh/adapters/mandrill.ex
fixes #168 
also syncs function name with the suggestion in #167
> Remove redundant decoding

- lib/swoosh/adapters/mandrill.ex
- test/swoosh/adapters/mandrill_test.exs
closes https://github.com/swoosh/swoosh/issues/171
> [feature] adds support to mandrill adapter for global merge vars and named templates

- lib/swoosh/adapters/mailgun.ex
- test/swoosh/adapters/mailgun_test.exs
I also tested this with sending actual emails with Mailgun and it works.
> Mailgun provider_option handling recipient variables

- README.md
This should make it clearer what is possible with the attachments in swoosh
> chore: added explanation for Swoosh.Attachment struct

- .gitignore
- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/postmark.ex
- lib/swoosh/adapters/sendgrid.ex
- lib/swoosh/adapters/sparkpost.ex
- mix.exs
- mix.lock
- test/support/adapter_case.ex
- test/swoosh/adapters/mailgun_test.exs
- test/swoosh/adapters/sparkpost_test.exs
- Removed Poison and added Jason dependency
- Modified all adapters to use Jason instead of Poison
- Modified AdapterCase to use Jason instead of Poison as json decoder
- Modified Mailgun & Sparkpost test
> Poison to Jason Migration

- config/config.exs
- lib/swoosh.ex
- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/postmark.ex
- lib/swoosh/adapters/sendgrid.ex
- lib/swoosh/adapters/sparkpost.ex
- test/support/adapter_case.ex
- test/swoosh/adapters/sparkpost_test.exs
Runs mix format in #217 to fix the long lines and brackets.
> Make json library configurable

- lib/swoosh.ex
> Add json library default to Application.get_env call

- lib/swoosh/adapter.ex
- lib/swoosh/adapters/amazon_ses.ex
- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/local/storage/memory.ex
- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/postmark.ex
- lib/swoosh/adapters/sendgrid.ex
- lib/swoosh/adapters/sendmail.ex
- lib/swoosh/adapters/smtp.ex
- lib/swoosh/adapters/smtp/helpers.ex
- lib/swoosh/adapters/sparkpost.ex
- lib/swoosh/adapters/xml/helpers.ex
- lib/swoosh/application.ex
- lib/swoosh/attachment.ex
- lib/swoosh/email.ex
- lib/swoosh/email/format.ex
- lib/swoosh/email/render.ex
- lib/swoosh/mailer.ex
- lib/swoosh/test_assertions.ex
merge #216 first
manually excluded some changes, probably better refactor the code instead of formatting it poorly.
> Run mix format

- lib/swoosh/adapters/postmark.ex
Inspired by the [Mandrill docs](https://hexdocs.pm/swoosh/Swoosh.Adapters.Mandrill.html).
> Added Postmark adapter docs for sending using templates

- README.md
> [skip ci] Mention Task.Supervisor

- lib/plug/mailbox_preview.ex
- lib/plug/templates/mailbox_viewer/index.html.eex
> Expose Attachments in Mailbox Preview

- lib/plug/mailbox_preview.ex
- lib/plug/templates/mailbox_viewer/index.html.eex
Ref #247.
Sorry this took a second to get up! Works been keeping me busy.
The placement and styling of the button can probably be configured from here; what's the general thoughts?
Here's what it looks like as is:
> Delete queued messages with button in preview

- mix.exs
I'd like to add cowboy 2 to the mix.
The current version (2.4) still has `Plug.Adapters.Cowboy` and the mail preview works.
> Add Cowboy2

- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/attachment.ex
- test/swoosh/adapters/mailgun_test.exs
- test/swoosh/adapters/sendgrid_test.exs
> Mailgun in-memory attachment support

- lib/swoosh/adapters/sendgrid.ex
- test/swoosh/adapters/sendgrid_test.exs
> Add mail_settings to enable sandbox_mode for sendgrid adapter

- lib/swoosh/adapters/sendgrid.ex
> Add documentation for sendgrid's sandbox mode

- lib/swoosh/adapters/socket_labs.ex
- test/swoosh/adapters/socket_labs_test.exs
Adapter for SocketLabs Injection API
> Socketlabs adapter

- CHANGELOG.md
- lib/swoosh/adapters/amazon_ses.ex
- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/postmark.ex
- lib/swoosh/adapters/sendgrid.ex
- lib/swoosh/adapters/socket_labs.ex
- lib/swoosh/adapters/sparkpost.ex
- lib/swoosh/api_client.ex
- lib/swoosh/email.ex
- test/support/adapter_case.ex
- test/support/conn_parser.ex
- test/swoosh/adapters/amazonses_test.exs
- test/swoosh/adapters/dyn_test.exs
- test/swoosh/adapters/mailgun_test.exs
- test/swoosh/adapters/mandrill_test.exs
- test/swoosh/adapters/postmark_test.exs
- test/swoosh/adapters/sendgrid_test.exs
- test/swoosh/adapters/sendmail_test.exs
- test/swoosh/adapters/smtp_test.exs
- test/swoosh/adapters/socket_labs_test.exs
- test/swoosh/adapters/sparkpost_test.exs
- test/swoosh/api_client_test.exs
> Extract api client

- lib/swoosh/adapters/gmail.ex
> Use Attachment get_content

- CHANGELOG.md
- lib/swoosh.ex
- mix.exs
> suppress warning for missing optional deps

- lib/plug/templates/mailbox_viewer/index.html.eex
- lib/swoosh/adapters/local/storage/memory.ex
> add sent_at when sending locally

- lib/swoosh/adapters/mailgun.ex
- test/swoosh/adapters/mailgun_test.exs
> add mailgun template support

- lib/swoosh/adapters/mailgun.ex
- mix.lock
- test/swoosh/adapters/mailgun_test.exs
> encode map and list only

- lib/swoosh/adapters/sendgrid.ex
close #416 
@danielscosta please take a look
Meaningful changes are only https://github.com/swoosh/swoosh/pull/419/files#diff-6fd5df4a59b213f0014cda474e9e7511R147-R158
> allow empty content in sendgrid

- lib/swoosh/adapters/mailjet.ex
- test/swoosh/adapters/mailjet_test.exs
> handle multiple "to" in mailjet

- .travis.yml
- lib/swoosh/adapters/test.ex
- mix.exs
- test/swoosh/adapters/test_test.exs
- test/swoosh/test_assertions_test.exs
> allow testing sending emails in other processes

- test/swoosh/adapters/test_test.exs
- test/swoosh/test_assertions_test.exs
needs v1.10.1 to not error in v1.10 build
> Fix test assertion

- lib/swoosh/adapter.ex
- lib/swoosh/adapters/mailjet.ex
- lib/swoosh/mailer.ex
- test/swoosh/adapters/mailjet_test.exs
workaround commits and CI issues...
> Deliver many

- lib/swoosh/adapters/sendgrid.ex
- test/swoosh/adapters/sendgrid_test.exs
> Revert "Return email body from Sendgrid adapter when emails are sent successfully"

- lib/swoosh/api_client.ex
- mix.exs
Apologies, I introduced a warning. I used the opportunity to fix other warnings too.
> Fix warnings on Elixir master

- lib/swoosh/adapters/mailgun.ex
- mix.lock
- test/swoosh/adapters/mailgun_test.exs
> Mailgun sending options

- lib/swoosh/adapter.ex
- lib/swoosh/adapters/test.ex
- test/swoosh/adapters/test_test.exs
- test/swoosh/email_test.exs
> Add delivery many to test client

- .formatter.exs
- lib/swoosh/adapters/smtp/helpers.ex
> Add support for custom Content-Type header

- lib/swoosh/adapters/amazon_ses.ex
> Use provider options to pass in security token

- lib/swoosh/adapters/smtp/helpers.ex
Resubmission of #538
Rebased by accident
> Support gen_smtp 1.0

- .github/workflows/elixir.yml
CI is failing for some random reason...
Totally works on my other project https://github.com/princemaple/cookie_jar/runs/1943665165
> bump erlang

- lib/swoosh/adapters/amazon_ses.ex
> Fix AWS SES adapter

- README.md
This PR improves the documentation of the README file and also
includes a mention that the user can configure `api_client` to false in
order to disable it.
Code blocks are _splitted_ to make easier to read and copy.
Closes https://github.com/swoosh/swoosh/issues/609
> Improve README.md - mention `api_client` as false

- README.md
* Comment that async emails are not necessary
* Comment the downsides of doing async
* Use Task.Supervisor by default
> Build upon async emails section

- lib/swoosh/adapters/amazon_ses.ex
Beside the provider options, we also fix some markdown to ensure
consistency.
> Add provider options doc for Amazon SES adapter

- lib/swoosh/adapters/mandrill.ex
> Add provider options doc for Mandrill adapter

- lib/swoosh/adapters/postmark.ex
> Update provider options doc for Postmark

- lib/swoosh/adapters/sendgrid.ex
> Update provider options doc for Sendgrid

- lib/swoosh/adapters/socket_labs.ex
> Add provider options doc for socketlabs

- lib/swoosh/adapters/sparkpost.ex
> Add provider options for Sparkpost

- README.md
- lib/swoosh/adapters/oh_my_smtp.ex
- test/swoosh/adapters/oh_my_smtp_test.exs
Closes #656 
I've been using this in one of my projects for a while, and verified it works (with attachments too). Please let me know if you have any feedback or changes; this is my first contribution here so not 100% sure of the code style etc.!
> add OhMySMTP adapter

- lib/swoosh/test_assertions.ex
> Mention E2E tests

- mix.exs
> suppress wanring

- lib/swoosh/adapters/mailjet.ex
> Make return type of deliver_many consistent

- lib/swoosh/adapters/customer_io.ex
- test/swoosh/adapters/customer_io_test.exs
Hi,
I need to send emails via customer.io transactional email API. This implementation might have some rough edges but is working for me.
> [ADAPTER] customer.io 

- CHANGELOG.md
- test/swoosh/email/recipient_test.exs
Found via `codespell -S deps -L feld`
> Fix more typos

- lib/swoosh/adapters/amazon_ses.ex
- lib/swoosh/adapters/customer_io.ex
- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/gmail.ex
- lib/swoosh/adapters/mail_pace.ex
- lib/swoosh/adapters/mailgun.ex
- lib/swoosh/adapters/mailjet.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/adapters/oh_my_smtp.ex
- lib/swoosh/adapters/sendgrid.ex
- lib/swoosh/adapters/sendinblue.ex
- lib/swoosh/adapters/smtp2go.ex
- lib/swoosh/adapters/socket_labs.ex
- lib/swoosh/adapters/sparkpost.ex
This Pull Request aims to better emphasize the need to use an API Client when integrating with API adapters.
> Add notes about API Client

- README.md
- lib/plug/mailbox_preview.ex
- lib/swoosh/adapters/amazon_ses.ex
- lib/swoosh/adapters/sendmail.ex
- lib/swoosh/adapters/smtp/helpers.ex
- mix.exs
- test/swoosh/adapters/amazonses_test.exs
- test/swoosh/adapters/mail_pace_test.exs
@adamu @thiamsantos 
https://elixirforum.com/t/elixir-v1-15-0-released/56584/4
> Fix BCC for adapters that depend on SMTP helper

- lib/swoosh/application.ex
Minor change but I hope it simplifies the code. :)
> Use concatenation to build sup children

- mix.exs
> depend on plug

- lib/swoosh/mailer.ex
> Update return value in docs

- README.md
Changes:
* Add information about Mailtrap adapter in README.md
* Fix pipe indentation for Scaleway adapter
> Add information about Mailtrap adapter in README.md

- lib/swoosh/adapters/proton_bridge.ex
> mention proton smtp, close #837

- lib/swoosh/adapters/mailgun.ex
- test/swoosh/adapters/mailgun_test.exs
@pirvudoru could you test this branch?
> Add template options

- lib/swoosh/adapters/dyn.ex
- lib/swoosh/adapters/scaleway.ex
Changes:
- fix comma issues on adapter config samples (Scaleway and Dyn)
> fix comma issues on adapter config samples

- lib/swoosh/adapters/smtp2go.ex
- test/swoosh/adapters/smtp2go_test.exs
> Support reply_to in smtp2go

- lib/swoosh/adapters/sendgrid.ex
- test/swoosh/adapters/sendgrid_test.exs
> Support multiple reply_to in sendgrid

- lib/swoosh/adapters/mailgun.ex
- test/swoosh/adapters/mailgun_test.exs
> Fix Mailgun adapter incompatibility with Finch

- lib/swoosh/adapters/amazon_ses.ex
- lib/swoosh/adapters/customer_io.ex
- lib/swoosh/adapters/local/storage/memory.ex
- lib/swoosh/adapters/logger.ex
- lib/swoosh/adapters/mailtrap.ex
- lib/swoosh/adapters/mandrill.ex
- lib/swoosh/email.ex
- lib/swoosh/test_assertions.ex
> Fix typos and improve language

- lib/swoosh/adapters/mua.ex
👋 
This PR ensures the "rendered" message has Date and Message-ID headers set. I haven't experienced it myself, but their absence seems to be causing issues for users who send emails directly (not via a relay which usually fills in these missing headers): https://github.com/ruslandoga/bamboo_mua/issues/53
> mua: add Date and Message-ID headers when missing

- lib/swoosh/adapters/ms_graph.ex
- test/swoosh/adapters/ms_graph_test.exs
> Handle direct URL specification on MSGraph.deliver

- lib/swoosh/adapters/mailjet.ex
- test/swoosh/adapters/mailjet_test.exs
I need this feature from mailjet that is not implemented.
https://dev.mailjet.com/email/guides/send-api-v31/#tag-email-messages
I added the possibility to add an event_payload
> feat(mailjet): add event_payload to provider options

- lib/swoosh/adapters/mua.ex
Context: https://github.com/swoosh/swoosh/pull/945#issuecomment-2532876675
> mua: fix default message-id

- test/integration/adapters/smtp_test.exs
~~I'll create a Google App password and rerun the integration test later today.~~
I used [Mailpit](https://github.com/axllent/mailpit) instead.
> mua: cleanup test

- lib/plug/mailbox_preview.ex
- lib/plug/templates/mailbox_viewer/index.html.eex
> fix priv path

- lib/swoosh/adapters/brevo.ex
- test/swoosh/adapters/brevo_test.exs
Implements batch email sending using Brevo's messageVersions API parameter. This allows sending multiple customized emails in a single API call.
Global-only parameters (shared across emails):
- sender
- attachment
- tags
- scheduledAt
Per-message parameters (customizable per email):
- to, cc, bcc
- replyTo
- subject, htmlContent, textContent
- templateId, params
- headers
Implementation detail: subject, htmlContent, textContent and templateId can be specified per message, but are required globally before overriding.
> Add deliver_many support to Brevo adapter
