swoosh/swoosh

lib/swoosh/mailer.ex
test/swoosh/mailer_test.exs

Swoosh.Mailer now supports runtime configuration using
{:system, "ENV_VAR"} tuples. The values will be fetched from the
process environment at runtime.
Fixes #50.

Add support for runtime configuration

---

lib/swoosh/adapter.ex
lib/swoosh/adapters/local.ex
lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/adapters/test.ex
test/swoosh/adapters/local_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs

Most services return useful information, and it makes sense to normalise the return values for each adapter.  This PR would replace all `:ok` returns with `{:ok, map}` where map will usually hold an ID provided by the service.
It's something of a suggestion at the moment.  @stevedomin :eyes: please!

Refactor adapter return values

---

lib/swoosh/adapter.ex
lib/swoosh/email.ex

This adds rudimentary typespecs in the `Swoosh.Email` module, in order to generate better documentation.
Also improves the typespecs of `Swoosh.Adapter`.

Initial typespecs

---

README.md
lib/swoosh/email.ex
lib/swoosh/in_memory_mailbox.ex
lib/swoosh/mailer.ex
test/swoosh/adapters/local_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs
test/swoosh/adapters/smtp_test.exs
test/swoosh/email_test.exs
test/swoosh/mailer_test.exs
test/swoosh/test_assertions_test.exs

Since `Swoosh.Email` is meant to be an opaque struct it makes sense
to provide a constructor for it.
We allow options to be passed to the function as it can be very
convenient at time (i.e testing).

Introduce Email.new/1

---

lib/swoosh/email.ex
lib/swoosh/email_helpers.ex
lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

This adds some code to make it possible to use assert_email_sent with certain fields rather than the whole email.

Allow to assert on email params

---

README.md

I believe this example is clearer than the previous one. The previous example actually fails if you don't construct the exact expected struct.

Updates README.md `assert_email_sent` example

---

lib/plug/mailbox_preview.ex
lib/plug/templates/mailbox_viewer/index.html.eex

We had some feedback that the formatting on the `Swoosh.Preview.Plug` can be confusing sometimes as we are using the `Inspect` protocol to display the fields in their Elixir native data format.
@lau fyi

Change format on preview Plug to be user-friendly

---

lib/swoosh/adapters/sendmail.ex
lib/swoosh/adapters/smtp.ex
test/swoosh/adapters/smtp_test.exs

dkim config can be added to config or email.provider_options or both, dkim config in email.provider_options overrides the one in the config.

Add dkim support to smtp adapter

---

lib/plug/mailbox_preview.ex
lib/plug/templates/mailbox_viewer/index.html.eex
lib/swoosh/adapters/logger.ex
lib/swoosh/email/format.ex
test/swoosh/adapters/logger_test.exs

This can be useful when you don't want to send real emails but still
want the Mailer to return successfully.
This was triggered by https://github.com/swoosh/swoosh/pull/72/

Add Logger adapter.

---

lib/swoosh/adapter.ex
lib/swoosh/adapters/local.ex
lib/swoosh/adapters/logger.ex
lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/adapters/sendmail.ex
lib/swoosh/adapters/smtp.ex
lib/swoosh/adapters/test.ex
lib/swoosh/mailer.ex
test/swoosh/adapters/mailgun_test.exs
test/swoosh/mailer_test.exs

References: https://github.com/swoosh/swoosh/issues/76
Let me know if you have any comments. Thanks.

Raise an error if the mailgun config is missing :domain or :api_key

---

lib/swoosh/mailer.ex

We should not pollute the application mailers with validation logic.

move email validation logic to base mailer

---

lib/swoosh/adapter.ex
lib/swoosh/adapters/local.ex
lib/swoosh/adapters/logger.ex
lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/adapters/sendmail.ex
lib/swoosh/adapters/smtp.ex
lib/swoosh/adapters/test.ex
lib/swoosh/mailer.ex
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs
test/swoosh/adapters/sendmail_test.exs
test/swoosh/adapters/smtp_test.exs
test/swoosh/mailer_test.exs

Currently we only return a {:error, reason} tuple if the adapter config
fails the validation. This decision was made in
https://github.com/swoosh/swoosh/pull/80 but is not ideal as users of
the library can't do much in that case and end up raising in their
application.

Raise on missing config

---

lib/swoosh/adapters/local/storage/memory.ex

This addresses an issue where the mailbox preview was rendered unusable behind an endpoint with lowercase path rewrite (a best practice).

Use case-insensitive Message-IDs in local storage memory

---

lib/swoosh/adapters/mailgun.ex
test/integration/adapters/mailgun_test.exs
test/swoosh/adapters/mailgun_test.exs

The Mailgun adapter expects a JSON response from the API when the response is a 401 (`:api_key` is invalid). Mailgun returns the string "Forbidden" instead, which causes a exception.
```
test wrong api key (Swoosh.Integration.Adapters.MailgunTest)
test/integration/adapters/mailgun_test.exs:29
** (Poison.SyntaxError) Unexpected token: F
stacktrace:
lib/poison/parser.ex:56: Poison.Parser.parse!/2
lib/poison.ex:83: Poison.decode!/2
(swoosh) lib/swoosh/adapters/mailgun.ex:37: Swoosh.Adapters.Mailgun.deliver/2
test/integration/adapters/mailgun_test.exs:39
```
Here is a proposed solution. I didn't actually check that the other status codes also return a string, but I think that's safe to assume that's the case. The docs https://documentation.mailgun.com/api-intro.html#errors are silent.

Handle 401 response from Mailgun

---

lib/plug/templates/mailbox_viewer/index.html.eex
lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/delivery_error.ex
lib/swoosh/mailer.ex
lib/swoosh/test_assertions.ex
test/integration/adapters/mailgun_test.exs
test/integration/adapters/smtp_test.exs
test/swoosh/adapters/logger_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs
test/swoosh/mailer_test.exs
test/swoosh/test_assertions_test.exs

Sometimes we want to raise when the delivery is unsuccessful. This PR introduces a new `deliver!/2` function that will raise if there is an API or SMTP error, or if the email validation failed (we will now only check that the `from` address is set, according to the RFC).
This PR introduces a couple of breaking changes:
* The API-based adapters now return a slightly different error payload: a `{status_code, body}` tuple instead of just the body.
* The `deliver/2` function will no longer raise if the email validation failed.
* We only validate that the `from` address is preset. We no longer check that there is a recipient (to, cc, bcc), that the subject is set, or that one of html_body or text_body is set.

Add Swoosh.Mailer.deliver!/2

---

lib/swoosh/adapters/mailgun.ex
test/swoosh/adapters/mailgun_test.exs

I wrote a small method + test that handles custom variables to send with the Mailgun posts. The format expects a map with key the variable name and value the json object. I also tested by sending actual mail and works well. Let me know if there are issues with style or anything!

Mailgun provider_option handling custom variables

---

lib/swoosh/adapters/local/storage/memory.ex

:crypto.rand_bytes/1 is deprecated on OTP 19 and issues a compilation
warning.

Use :crypto.strong_rand_bytes/1

---

.travis.yml
README.md
lib/swoosh/adapters/local/storage/memory.ex
lib/swoosh/email.ex
lib/swoosh/email_helpers.ex
lib/swoosh/mailer.ex
test/integration/adapters/mailgun_test.exs
test/integration/adapters/postmark_test.exs
test/integration/adapters/sendgrid_test.exs
test/integration/adapters/smtp_test.exs
test/swoosh/adapters/local_test.exs
test/swoosh/adapters/logger_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs
test/swoosh/adapters/sendmail_test.exs
test/swoosh/adapters/smtp_test.exs
test/swoosh/email_test.exs
test/swoosh/mailer_test.exs
test/swoosh/test_assertions_test.exs

Hello,
I felt that I had probably send you enough spam and made the domain in integration tests configurable. 
I also changed the e-mail addresses in tests from, i. e. tony@stark.com to tony.stark@example.com. I felt uncomfortable with the possibility of them leaking into production code and possibly interfering with real people.
I hope these changes are useful. Thx!

Tests: make hardcoded domain configurable and use RFC-compliant @example.com

---

lib/swoosh/adapters/postmark.ex
lib/swoosh/email.ex
test/integration/adapters/postmark_test.exs
test/swoosh/adapters/postmark_test.exs

[Postmark](https://postmarkapp.com/) allows using [predefined templates](http://developer.postmarkapp.com/developer-api-templates.html) instead of sending `HTML` or `TEXT` body.
To do that, we need to provide 2 things:
- `TemplateId` - which is the ID of template to use when sending an email defined in Postmark account
- `TemplateModel` - which presents the model to be applied to the specified template to generate `HtmlBody`, `TextBody`, and `Subject`
This PR is supposed to give users a possibility to send email using these templates instead of defining custom templates from the code.

Handle templates for postmark

---

lib/swoosh/adapters/postmark.ex
test/swoosh/adapters/postmark_test.exs

For some reason it wasn't respected. The API documents that it should be: 
> The From and To fields are able to accept name, in the format of `John Doe <email@example.com>`
http://developer.postmarkapp.com/developer-send-api.html#message-format

Respect from name in the postmark adapter

---

README.md

```
==> swoosh
Compiling 22 files (.ex)
warning: function :mimemail.encode/2 is undefined (module :mimemail is not available)
lib/swoosh/adapters/smtp/helpers.ex:17
```
`:mimemail` is defined in `gen_smtp`
Maybe wrap `SMTP.Helpers` and `Swoosh.Adapters.Sendmail` with `Code.ensure_loaded?` as well?

Update README.md re: when to include gen_smtp

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

Howdy! We use SendGrid's templates at work, so I just needed to support a couple of extra fields through `put_provider_option` to make it work. The template data can be passed in like this:
```
|> put_provider_option(:template_id, "some-guid")
|> put_provider_option(:substitutions, %{"-name-" => "Steve Rogers"})
```

Support SendGrid templates and substitutions

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

This makes it possible to attach categories: 
`|> put_provider_option(:categories, ["hello", ...])`

Support SendGrid categories

---

lib/swoosh/adapters/mailgun.ex
test/swoosh/adapters/mailgun_test.exs

This pull request adds support for mail headers in the Mailgun adapter, sending the headers added with the function `Email.header/3` according with the Mailgun documentation (https://documentation.mailgun.com/api-sending.html#sending)
> h:X-My-Header h: prefix followed by an arbitrary value allows to append a custom MIME header to the message (X-My-Header in this case). For example, h:Reply-To to specify Reply-To address.

Support for mail headers in Mailgun adapter

---

lib/swoosh/mailer.ex
mix.lock
test/swoosh/mailer_test.exs

Configs are loaded at runtime.
Module configs are kept, still having higher priority.
Configs now are read in the following order, the later ones take priority:
1. mix configs
```elixir
config :my_app, MyMailer, # the configs
```
2. module configs
```elixir
defmodule MyMailer do
use Swoosh.Mailer, otp_app: :my_app, # other configs
end
```
3. function configs
```elixir
MyMailer.deliver(email, the_custom_configs)
```
4. system env
All the `{:system, "ENV_VAR"}` are finally loaded
close #84

Full runtime config support

---

lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/postmark.ex
test/swoosh/adapters/mailgun_test.exs

If the name portion of a recipient contains a comma, weird things will happen. With multiple recipients, some of them will be chopped off without any warnings or errors.
This changes the formatting from
`Acme Inc, headquarters <hq@acme.com>`
to
`"Acme Inc, headquarters" <hq@acme.com>`
Ref: https://stackoverflow.com/questions/35370571/how-to-add-a-comma-to-a-mailgun-from-field-for-outbound-emails
Ref: http://www.rfc-editor.org/rfc/rfc2822.txt
> Note that the display names for Joe Q. Public and Giant; "Big" Box needed to be enclosed in double-quotes because the former contains the period and the latter contains both semicolon and double-quote characters (the double-quote characters appearing as quoted-pair construct).
This bit me HARD, so I hope you'll consider this PR.
Thanks!

Quote name portion of recipient for Mailgun

---

lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/adapters/sparkpost.ex
test/swoosh/adapters/mandrill_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/adapters/sendgrid_test.exs
test/swoosh/adapters/sparkpost_test.exs

Fixes #153 and adds support across the board.

Add support for custom email headers across all adapters

---

lib/swoosh/adapters/smtp.ex
test/swoosh/adapters/smtp_test.exs

Enforce config values having correct types before passing to gen_smtp

---

README.md
lib/swoosh/adapters/amazon_ses.ex
lib/swoosh/adapters/xml/helpers.ex
test/swoosh/adapters/amazonses_test.exs
test/swoosh/adapters/xml/helpers_test.exs

Attempt at adding a new Amazon SES adapter to send out basic emails. Uses their SendRawEmail interface on their query api since that is the interface that allows for attachments.
Addresses #6

Amazon SES Adapter

---

lib/swoosh/adapters/smtp/helpers.ex
lib/swoosh/attachment.ex
test/swoosh/attachment_test.exs

When you add an attachment, sometimes, you need to add some custom headers (i.e. for a ical). This PR add a (optional) list of custom headers when a new attachment struct is created.

add optional headers to attachment

---

lib/swoosh/adapters/mandrill.ex
test/swoosh/adapters/mandrill_test.exs

when sending an email using a template we need to hit a different endpoint `/messages/send-template.json` also we need to specify a `template_content` for the sending template and that is obligatory but can be blank.
closes #174

Add support for send-template endpoint

---

lib/swoosh/adapters/smtp/helpers.ex
lib/swoosh/attachment.ex
test/integration/adapters/smtp_test.exs

Added "data" key in Swoosh.Attachment so you can add "in memory" data as attachment. Added this feature for SMTP adapter.

add in memory attachment for smtp adapter

---

lib/swoosh/adapters/sendmail.ex
lib/swoosh/mailer.ex

As soon as a module uses Swoosh.Mailer, dialyzer warns about:
> lib/my_mailer.ex:3: The pattern {'error', _@5, _@6} can never match the type {'error',_} | {'ok',_}
This happens because the case into mailer.ex looks for a `triple` which never happens in any of the adapters. As confirmation the deliver callback typespec does not specify such triple.
This PR fixes that and also fixes the return value from the sendmail.ex deliver fun, because Port.close returns :true while the specs expects at least :ok

Fix dialyzer warnings when using Swoosh.Mailer

---

lib/swoosh/adapters/smtp/helpers.ex

Right now, if both text and html are given along an attachment, the smtp adapter builds a single level multipart/mixed , resulting into text and html shown at the same time.
Instead, html and text must be a multipart/alternative *inside* the multipart/mixed which holds the attachment.
This PR fixes that.

Fix text/html alternative multipart when having also an attachment

---

lib/swoosh/adapters/mandrill.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/adapters/sendgrid.ex
lib/swoosh/adapters/sparkpost.ex
lib/swoosh/attachment.ex
lib/swoosh/attachment_content_error.ex
lib/swoosh/email.ex
test/integration/adapters/smtp_test.exs

Close #179 
Fixes #183 
This PR will allow sending attachments from in-memory data in all adapters.
However, we only provide one convenience function `Attachment.new` that works with `path`, and `Plug.Conn` if it's included in the code base. I filed a separate issue #181 for further improvements that will allow in-memory data and maybe other ways of adding attachments in the future.

Refactor to use get_content in all adapters

---

lib/swoosh/adapters/amazon_ses.ex

amz_date produces incorrect date stamps without leading zeroes for days and months. This is a quick fix for that issue.

Fix amz_date implementation

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

See
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Response-Example
for the description of the different headers.

Return the message id from the sendgrid adapter mirroring other adapters

---

lib/swoosh/adapters/smtp.ex

Hello,
I added `no_mx_lookups` option to `smtp` config.
This option can help when you don't want to connect to the returned mx's of relay.
The `no_mx_lookups` is not mentioned in the `gen_smtp` README, but see https://github.com/Vagabond/gen_smtp/blob/master/src/gen_smtp_client.erl#L136 for more details.
It's now possible to pass this option, but making it clearer in the documentation can help other people.
What do you think? Would it be valid?
Thanks.

Add no_mx_lookups to smtp config

---

lib/swoosh/adapters/sparkpost.ex
test/swoosh/adapters/sparkpost_test.exs

it's currently never allowed because of the existence of inline_images key
changing it to conditionally adding attachment keys resolves the problem
fix #207

Fix text only body

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

Thanks for the great library!
This PR adds support for the `asm` field in the SendGrid adapter ([unsubscribe groups behaviour](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html))

Add SendGrid asm field

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

While using swoosh I wanted to assert with a regex that a particular string was being sent in the html_body. Currently the only way I could make it work is:
```
assert_received({:email, email})
assert email.html_body =~ regex
```
While it kind of works it doesn't read so well so I'm proposing adding regexp support
so we will be able to do things like:
```
assert_email_sent(to: {"Bob", "example@example.com"}, text_body: ~r/Hi Bob!/)
```
edit: I updated the PR so it no longer has three new options and pattern matches the value on regex struct type instead

Add regex email body test assertions

---

lib/plug/templates/mailbox_viewer/index.html.eex

Also made sure that _some_ content renders for Subject. Without it, the `.col-sm-10` element will have zero height and the whole layout is broken.
This is how it looks now:

Display provider_options in mailbox_viewer

---

.travis.yml

~Since we have this config turned on:~
~> **Require branches to be up to date before merging**~
~> This ensures the branch has been tested with the latest code on master.~
~It's redundant to test both a branch and a PR.~
Actually the above don't really relate.
This change has no effect on external contributors whatsoever, as their branches don't trick a branch test, only a PR test.
This only saves us maintainers from having to wait for twice (or more) the time on new PRs because of concurrent build limit.
caveat: this does mean that you have to send a WIP PR to kick off CI for you branches, but we test locally anyways.

Disable travis CI for branches other than master, in favor of PR tests

---

mix.exs

#242 
This feature was introduced in Elixir 1.4
And Swoosh does require "~> 1.4" 😄

Change to use extra_applications

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

- according to [sendgrid api doc](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send), for handlebar substitutions, request body should contain `dynamic_template_data` inside `personalizations` object

sendgrid - handlebar substitutions with dynamic_template_data

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

This fixes #274.
Changes:
* added `assert_email_sent/0` that asserts any email was sent
* added `refute_email_sent/0` (macro) that asserts no email was sent ("alias" of `assert_no_email_sent/0`)
* added `refute_email_sent/1` (macro)
Besides implementing the simple pattern matching with `refute_email_sent(pattern)` - which requires exact matching on inner data structures - I took the opportunity to also add a `refute_email_sent(attributes)` version that creates a pattern (a Map) that automatically converts single values to single element lists while formatting the addresses (`to: "email@example.com"` becomes `to: [{"", "email@example.com"}]`).
Some notes:
* `mix format` changed several lines
* added `@spec`s
* added a stricter pattern matching on `assert_email_not_sent/1` (since it pins …

Improve TestAssertions

---

lib/swoosh/adapters/amazon_ses.ex
test/swoosh/adapters/amazonses_test.exs

See: https://docs.aws.amazon.com/ses/latest/APIReference/API_MessageTag.html
Closed: https://github.com/swoosh/swoosh/issues/282

Add support for AWS SES tags

---

lib/swoosh/adapters/sparkpost.ex
test/swoosh/adapters/sparkpost_test.exs

This PR adds support for SparkPost templates, as requested in #275 .
They can be used like this:
```elixir
new()
|> from("tony.stark@example.com")
|> to("steve.rogers@example.com")
|> subject("Hello, Avengers!")
|> put_provider_option(:template_id, "my-first-email")
|> put_provider_option(:substitution_data, %{
first_name: "Peter",
last_name: "Parker"
})
```

Add support for SparkPost templates

---

README.md

Adapter table not being displayed correctly in hexdocs, even though it's fine in the GH repo README.
Should now be fixed.

Update README for 

---

lib/swoosh/adapters/local/storage/memory.ex

I've been playing with the Test adapter and found this issue #258.
This should resolve it, by embedding the raw data of the attachment in the `Genserver` "storage".
I didn't convert to `:base64` to keep compatible with the rendering side where it doesn't decode: https://github.com/swoosh/swoosh/blob/e3beba436797850ceb664ceee8d5178487a82617/lib/plug/mailbox_preview.ex#L73-L76
Please let me know if you need any changes made.

Store attachment content in Memory when using local adapter

---

lib/swoosh/adapters/local/storage/memory.ex

Thought it would be most clear to just show the diff for the best solution we came up with for a problem we are encountering to see if it could be merged. To my knowledge there is not much downside to doing this but would enable supporting development environments that have multiple app instances running (like ours in order to closely match our multi-server production environment).
The problem is in a two server environment there will be two instances of `Swoosh.Adapters.Local.Storage.Memory` and viewing the dev mailbox there will not list the full list of emails and when click on an email to view it there's a 50% it will go to the wrong server and not show the email.
Some other things we tried to avoid changes to Swoosh:
- **Direct all /dev/mailbox traffic to one app server** - Any app …

Multi-server support for local adapter

---

.travis.yml

Revert this later when integration tests are fixed

Temporarily skip integration tests

---

lib/swoosh/application.ex
mix.exs

`Plug.Adapters.Cowboy` has been deprecated and replaces with the `plug_cowboy` package.
If `plug_cowboy` version 2.0.0 or higher is installed, the preview server will not start because `child_spec/4` has been removed.
This changes the optional dependency to use the `plug_cowboy` package (which will indirectly require plug), and changes to using the `child_spec/1` function which is available in both versions 1 and 2 of `plug_cowboy`

Allow preview server to start when using plug cowboy version 2

---

lib/swoosh/adapters/mailjet.ex
test/swoosh/adapters/mailjet_test.exs

1. Added basic set of tests
2. You can use `put_provider_option(:template_id, "template id")` to send `TemplateID` field.
3. Error responses are JSON-decoded. By the documentation, even 500s are JSONs.
It is an improvement to https://github.com/swoosh/swoosh/pull/259

Add tests to Mailjet adapter. Allow sending template id.

---

README.md
lib/swoosh/adapters/amazon_ses.ex
mix.exs

bump gen_smtp version to work with erlang 21, update readme

---

README.md

Changing the preview port is not mentioned in any of the swoosh documentation here or on hex. This took me a while to dig up. Hopefully it will save others time in the future.

Add documentation for :preview_port

---

lib/swoosh/adapters/mandrill.ex

You can use mailchimp and handlebars languages for mandril templates.
This PR provides missed option to select language.

Add merge language argument

---

lib/swoosh/adapters/mailjet.ex
test/swoosh/adapters/mailjet_test.exs

Add `TemplateErrorDeliver` and `TemplateErrorReporting` `provider_options` to mailjet

Add mailjet error delivery config

---

lib/swoosh/adapters/mailjet.ex
test/swoosh/adapters/mailjet_test.exs

I forgot to add the `CustomID` API option which we use. 
Doc is here: https://dev.mailjet.com/guides/#send-an-email-with-a-custom-id
I took the chance to make a little refactoring in the mailjet test file.

Added :custom_id mailjet API option.

---

lib/swoosh/adapters/postmark.ex
test/integration/adapters/postmark_test.exs
test/swoosh/adapters/postmark_test.exs

You can now add a tag to postmark emails.

Add postmark tag

---

lib/swoosh/adapters/smtp/helpers.ex

Using a struct to enforce defaults isn't enough, in our application it made it's way through here somehow with a nil (due to bad cache syncing for translations) that and I ended up with a super helpful error of `(FunctionClauseError) no function clause matching in :mimemail.rfc2047_utf8_encode/4`
Digging into that:
```
The following arguments were given to :mimemail.rfc2047_utf8_encode/4:
nil
'?Q?8-FTU?='
10
[]
```
This is useless, would anyone of guessed this was from subject being nil?!

Make a default of "" in subject to prevent really hard to debug errors

---

lib/swoosh/adapters/sparkpost.ex

This adds the ability to set `options` as defined in the SparkPost transmissions API documentation:
https://developers.sparkpost.com/api/transmissions/#header-request-body
Note that the `options` value is passed as-is to the JSON body sent to SparkPost.
I could not find any test for the SparkPost adapter, but in case I missed something and additional tests are needed, please let me know.

Add ability to set SparkPost transmission options

---

lib/swoosh/application.ex

Before this patch it may not have been started e.g. in an umbrella:
say you correctly configured with `local: true`, but because a domain
app may not depend on plug & cowboy, we returned empty children instead
of the local adapter (if configured)

Ensure local storage adapter is started if enabled

---

README.md

While reading the README I noticed the attachments section wasn't syntax highlighted.
This PR adds a code fence around it.

Add syntax highlighting to attachments example

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

This allows to easily configure personalizations directly through `provider_options`, was useful for us in order to send transactional email with different emails without each recipient seeing the full list.

Sendgrid: accept personalizations directly as provider_options

---

lib/swoosh/adapters/gmail.ex

Closes #489
Also adding `access_token` existence to config looks helpful

Remove misleading Swoosh.Adapters.Gmail clause about omitting `from` while building email

---

lib/plug/templates/mailbox_viewer/index.html.eex

When used in a router pipeline that includes the :protect_from_forgery plug, a CSRF token is required for the "Delete Message Queue" functionality to work.

Add CSRF token to dev preview mailbox (fixes #381)

---

README.md

Updates the instructions in the Readme for setting up layout. It removes a deprecation warning.
Phoenix logs:
```
.warning: Rendering the child template from layouts is deprecated. Instead of:
<%= render(@view_module, @view_template, assigns) %>
You should do:
<%= @inner_content %>
```

Updates readme instructions for setting up layout

---

lib/swoosh/adapters/amazon_ses.ex

In case you use IAM role for authenticating AWS requests you can fetch
temporary access_key and secret_key from that role, but you also need to
include additional X-Amz-Security-Token header to that request.
Docs: [Http request signature](https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html)

Add support for temporary credentials in AmazonSES

---

README.md
mix.exs

List of changes:
- Use common source url
- Word wrapping the module description
- Add missing contributing and code of conduct doc
- Reformat line wrapping
- Fix typos
- Fix code example long line overflow
- Remove unused Travis CI badge
- Badges and more badges
- Add changelog link to hex module info page
- Add module requirements

Misc fixes and changes to HTML doc generation

---

lib/swoosh/adapters/smtp/helpers.ex

Support gen_smtp 1.0, which was [released](https://github.com/gen-smtp/gen_smtp/releases/tag/1.0.0) recently. The changelog for release contains a breaking change for `mimemail:parameters()`.
In https://github.com/gen-smtp/gen_smtp/pull/190/files#diff-8c203e5d2065d87650bec83bac9032a9ca7b14e6ae74fe3eac1c92cc00923ce7R706, the signature of `:mimemail.encode/2` function got changed by replacing a keyword list with map.
This commit follows the change in gen_smtp.

Support gen_smtp 1.0

---

lib/swoosh/adapters/logger.ex
lib/swoosh/adapters/smtp.ex
lib/swoosh/adapters/sparkpost.ex
lib/swoosh/email/render.ex

I noticed one place where the code is mapping over lists, then joining them (two iterations), so I did a search and found a few more. While they are small and the performance gain is probably negligible, any little bit helps? I don't think it's any more difficult to reason about and I think it's also good to promote Enum.map_join/3 as a "best practice". Thanks for Swoosh!

Utilize Enum.map_join/3

---

lib/swoosh/adapters/mailgun.ex
test/swoosh/adapters/mailgun_test.exs

The current way in `Swoosh.Adapters.Mailgun` to send variables is to use a form parameter, which is not recomended as it’s limited to simple key value data. If you have arrays, dictionaries in values or complex json data you have to supply variables via X-Mailgun-Variables header, which is implemented on this PR.
https://documentation.mailgun.com/en/latest/user_manual.html#templates

Add support for arrays in mailgun custom_vars

---

README.md
lib/swoosh/adapters/sendinblue.ex
test/integration/adapters/sendinblue_test.exs
test/swoosh/adapters/sendinblue_test.exs

DRAFT
This PR adds an adapter for sendinblue (transactional emails only).
Related to #537
Todo:
@princemaple Can you help here?

Add sendinblue adapter

---

lib/plug/templates/mailbox_viewer/index.html.eex

I think in the [new version of bootstrap](https://github.com/swoosh/swoosh/commit/854fcc09a6a4892280e4bafe83468270704f0ba2) the offset class was changed, because of that the preview in the new version is breaking. 
References:
- https://getbootstrap.com/docs/4.6/layout/grid/#offsetting-columns

Fix Mailbox Viewer

---

README.md
lib/plug/mailbox_preview.ex
test/plug/mailbox_preview_test.exs

Closes #61 
As [pointed out in the issue](https://github.com/swoosh/swoosh/issues/61#issuecomment-638032058) we have two alternatives, add JSON for the existing endpoint or create a new one specific for the JSON payload. Initially I thought in adding a different endpoint may be simpler for the daily usage, as we will not have to remember to pass the accept header to get the expected payload, a different endpoint seems to be more explicit. However I'm open to change to the a single endpoint in case is considered better for swoosh.

Add json endpoint for mailbox preview

---

lib/swoosh/adapters/test.ex
lib/swoosh/test_assertions.ex
test/swoosh/adapters/global_test_test.exs

Closes  #66
The approach took is really similar to one [suggested in the issue](https://github.com/swoosh/swoosh/issues/66#issuecomment-387516542).
I also considered a allowance mechanism similar to what ecto and mox do, but IMO we can accomplish a similar result with a much simpler solution. For the use case of swoosh, just making sure that the messages are sent to the test process seems to be enough to allow users to do integration tests.

Support integration tests

---

CHANGELOG.md

Thanks for your work! Only a minor thing, but from the link title this is the intended linking, I guess? At least this is what I would have expected.

Link to pre-1.0/changelog.md instead of readme.md

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

Adds support for Sendgrid `tracking_options` as per docs at https://sendgrid.com/docs/api-reference/
```elixir
new() |> put_provider_option(:tracking_settings, %{subscription_tracking: %{enable: false}})
```

Support Sendgrid `tracking_settings` as per API docs

---

README.md
lib/plug/mailbox_preview.ex

close #569 
cc @LostKobrakai 
I'm keeping the config because I haven't checked how it works under multiple forward. If you have more information, maybe we can remove it altogether.

Remove base_path in favor of using script_name from Plug.Conn

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

Closes #573.
The function allows setting expectation on any condition, most notably on provider options.
The function is not supported for `assert_email_not_sent` nor `refute_email_sent` because they translate to pattern matching inside a `receive do ... end` block.

Allow passing an anonymous function to assert_email_sent

---

mix.exs

Suppress warning caused by `Mail.Message.put_header`

---

README.md
lib/swoosh/application.ex

I getting the following error sometimes when the mailbox server is been started.
```
19:15:50.639 [info] Running Swoosh mailbox preview server with Cowboy using http on port 4001
19:15:50.643 [info] Application swoosh exited: exited in: Swoosh.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (UndefinedFunctionError) function Plug.Swoosh.MailboxPreview.init/1 is undefined (module Plug.Swoosh.MailboxPreview is not available)
Plug.Swoosh.MailboxPreview.init([])
(plug_cowboy 2.5.0) lib/plug/cowboy.ex:371: Plug.Cowboy.dispatch_for/2
(plug_cowboy 2.5.0) lib/plug/cowboy.ex:319: Plug.Cowboy.to_args/5
(plug_cowboy 2.5.0) lib/plug/cowboy.ex:228: Plug.Cowboy.child_spec/1
(swoosh 1.3.10) lib/swoosh/application.ex:29: Swoosh.Application.start/2
(kernel 7.3) …
```

Require plug cowboy to start mailbox server

---

README.md
lib/swoosh/mailer.ex
mix.exs
test/swoosh/mailer_test.exs

This PR adds the following telemetry events:
- `[:swoosh, :deliver, :start]`: occurs when `Mailer.deliver/2` starts
- `[:swoosh, :deliver, :stop]`: occurs when `Mailer.deliver/2` succeeds
- `[:swoosh, :deliver, :exception]`: occurs when `Mailer.deliver/2` fails
- `[:swoosh, :deliver_many, :start]`: occurs when `Mailer.deliver_many/2` starts
- `[:swoosh, :deliver_many, :stop]`: occurs when `Mailer.deliver_many/2` succeeds
- `[:swoosh, :deliver_many, :exception]`: occurs when `Mailer.deliver_many/2` fails
Example of capturing a count of emails that succeed and fail:
```elixir
defmodule MyHandler do
def handle_event([:swoosh, :deliver, :stop], _measurements, metadata, _config) do
StatsD.increment("mail.sent.success", 1, %{mailer: metadata.mailer})
end
def handle_event([:swoosh, :deliver, …
```

Adds telemetry to Mailer.deliver & Mailer.deliver_many

---

lib/swoosh/adapters/smtp.ex

I ran afoul of this after deploying my app to production.
The fact that the beam crashed on this with no clear error message took me some time to investigate.

Clarify that you need to add :gen_smtp as a dependency

---

lib/swoosh/adapters/mailgun.ex

We update and standardize the provider options and add a sample code
example on how to use these provider options.

Update provider options doc for Mailgun adapter

---

lib/swoosh/adapters/mailgun.ex
lib/swoosh/adapters/mailjet.ex

Beside the provider options, we also fix typo and add code example.

Add provider options doc for Mailjet

---

lib/swoosh/adapters/sendinblue.ex

We also update the link to the official API doc.

Update provider options doc for Sendinblue

---

config/config.exs

`bypass` is only used on test env, but is configured on all envs.

Config bypass only on test

---

lib/swoosh/adapters/mailgun.ex

It took me some time to figure out I had to change the `base_url` to get my configuration to work.

Add configuration options to Mailgun documentation

---

lib/swoosh/adapters/oh_my_smtp.ex
lib/swoosh/adapters/postmark.ex
lib/swoosh/attachment.ex
lib/swoosh/email.ex
test/swoosh/adapters/oh_my_smtp_test.exs
test/swoosh/adapters/postmark_test.exs
test/swoosh/attachment_test.exs

Closes #658 
Added some tests for this (for OhMySMTP and Postmark, the only adapters that handle inline images). Also tested manually with OhMySMTP and it works.

allow custom CIDs for inline attachments

---

lib/swoosh/adapters/postmark.ex
test/swoosh/adapters/postmark_test.exs

While working on a feature to send a number of emails using `deliver_many`, I was referencing [Postmark's docs on sending batch emails](https://postmarkapp.com/developer/api/email-api#send-batch-emails). I had assumed that the value returned by the Postmark adapter's `deliver_many` implementation (and also `deliver`) would return the API response using something like `Jason.decode!`, so my original implementation was expecting the String keys matching the casing found in the Postmark API response. I was surprised to find the response was a map with atomized keys and only a subset of the API response. Digging into the Postmark adapter's source, I found the bit of code that was performing the JSON decoding and mapping a subset of values. I need to extend that return value with the "To" …

Add fields to Postmark `deliver_many` response

---

lib/swoosh/adapters/smtp/helpers.ex
test/swoosh/adapters/gmail_test.exs
test/swoosh/email/smtp_test.exs

Even though [RFC5234](https://www.rfc-editor.org/rfc/rfc5234#section-2.3) says email headers are case-insensitive, prefer to use the value given by [RFC1341](https://datatracker.ietf.org/doc/html/rfc1341#page-5).
For instance, [rspamd doesn't like `Mime-Version`](https://github.com/rspamd/rspamd/blob/f24d59a607066d339597a1a537f3171c9350a1d6/rules/headers_checks.lua#L589-L596).

Rename Mime-Version header to MIME-Version

---

lib/swoosh/adapters/smtp/helpers.ex

I need to send emails with only bcc addresses, but when I tried to send with an empty list in `to` attribute I got:
```sh
** (MatchError) no match of right hand side value: {:error, {999999, :smtp_rfc5322_parse, ['syntax error before: ', []]}}
(gen_smtp 1.2.0) /__w/app/app/deps/gen_smtp/src/mimemail.erl:999: :mimemail.encode_header_value/2
(gen_smtp 1.2.0) /__w/app/app/deps/gen_smtp/src/mimemail.erl:963: :mimemail.encode_headers/1
(gen_smtp 1.2.0) /__w/app/app/deps/gen_smtp/src/mimemail.erl:964: :mimemail.encode_headers/1
(gen_smtp 1.2.0) /__w/app/app/deps/gen_smtp/src/mimemail.erl:210: :mimemail.encode/2
(swoosh 1.6.6) lib/swoosh/adapters/amazon_ses.ex:165: Swoosh.Adapters.AmazonSES.generate_raw_message_data/2
(swoosh 1.6.6) lib/swoosh/adapters/amazon_ses.ex:134: …
```

Allow send email with empty 'To' header

---

lib/swoosh/adapters/sendgrid.ex
test/swoosh/adapters/sendgrid_test.exs

For sending scheduled emails through sendgrid, two body fields were missing. This PR adds `send_at` and `batch_id` to sendgrid adapter `provider_options_body_fields`

sendgrid add support for scheduling emails

---

lib/swoosh/mailer.ex

Failures handled by adapters won't trigger an `:exception` event, but it will include an `:error` key on the `:stop` metadata. 
We noticed that we our log handler wasn't logging errors after a [Mailgun incident](https://status.mailgun.com/incidents/gcm3zw1lvfl4) and the adapter was returning `{:error, term}` instead of raising

Update Telemetry example to mention errors on `:stop`

---

lib/swoosh/adapters/sendinblue.ex
test/swoosh/adapters/sendinblue_test.exs

adds new provider param for sending scheduled emails via `sendinblue` adapter.
Please note this feature is currently a public beta.

add schedule_at provider param for sendinblue

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

Added headers clause for `assert_equal` and some tests to check this functionality.

Support assertions for headers

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
lib/swoosh/adapters/smtp.ex
lib/swoosh/adapters/sparkpost.ex
test/swoosh/adapters/smtp_test.exs

See a detailed description of the rules is available at
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

Fix markdown issues and typos

---

lib/swoosh/adapters/gmail.ex
lib/swoosh/adapters/socket_labs.ex

Fixes a small typo in gmail and socket labs adapter documentation.

Fix typos in gmail and socket labs adapters

---

lib/swoosh/adapters/mailjet.ex

I can see that cid is not honoured in other adapters as well, but I just checked the Mailjet docs for how to pass that param in there.

Set attachment's ContentId in Mailjet

---

lib/swoosh/adapters/sendinblue.ex

The example uses the wrong key and passes a map.

doc: correct tags example for Adapters.Sendinblue

---

lib/swoosh/adapters/local/storage/manager.ex
lib/swoosh/adapters/local/storage/memory.ex
lib/swoosh/application.ex

Connecting/disconnecting nodes to a cluster will cause multiple restarts of the `Memory` adapter GenServer making [exceeding the `max_restarts` of the top-level supervisor](https://hexdocs.pm/elixir/1.13/Supervisor.html#init/2) easy thus crashing the application.
This adds a manager GenServer that will monitor the global adapter instead of linking to it to avoid crashing it when a node disconnects and trigger the above condition.
The bug is triggered by having two nodes in a cluster and running this code:
```elixir
def trigger do
Node.connect(:"node1@127.0.0.1")
Process.sleep(400)
Node.disconnect(:"node1@127.0.0.1")
Process.sleep(400)
Node.connect(:"node1@127.0.0.1")
Process.sleep(400)
Node.disconnect(:"node1@127.0.0.1")
end
```
Not sure how I can add a test case for this so I'll look …

Fix crashes caused by the memory GenServer restarts

---

lib/swoosh/adapters/postmark.ex
test/swoosh/adapters/postmark_test.exs

Postmark allows overriding the "Open" and "Click" tracking on a per email basis. This commit allows (optionally) setting the required fields in the API calls via the provider options.

Postmark: Support per email tracking options

---

CONTRIBUTING.md

Spotted this while reading the docs. Find-and-replace didn't spot any other instances :)

Fix typo in contributor guidelines

---

README.md
lib/swoosh/adapters/proton_bridge.ex

The Protonmail bridge is a local SMTP server that bridges to Protonmail.
This adapter is a thin layer on-top the existing SMTP adapter.
Even if this adapter is trivial, I hope people will find it useful.
Ref: https://proton.me/mail/bridge

Add support for Protonmail Bridge

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

This PR adds the `assert_emails_sent`  function (#560 ).
- add a function to make it easier to test `deliver_many`

Add assert_emails_sent

---

lib/swoosh/test_assertions.ex
test/swoosh/test_assertions_test.exs

Hi!
I am still a beginner in Elixir/Phoenix/Swoosh, so it took me a while to understand why a regexp-based assertion didn't work with e-mail subject.
I found out, as you can tell, and I think it should be supported, hence this PR!
Thank you for a very beginner-friendly library!
/Stavros

Allow Regexp assertions for subjects

---

lib/swoosh/adapters/smtp/helpers.ex
test/plug/mailbox_preview_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/email/smtp_test.exs

Mail clients expect an inline attachment to be grouped with
the HTML in a "multipart/related" section, if not the
attachment will show up as both "inline" and as a regular
attachment.

When adding an inline-attachment an extra section is needed.

---

lib/swoosh/x_test_assertions.ex
test/swoosh/x_test_assertions_test.exs

❗ This isn't backwards compatible.
I had a few complaints about current implementation of test helpers - `refute` working only on literal params, assertions consuming emails from queue, kinda bad error reporting so I decided to take a spin on it.
It's a bit worse memory-wise because we keep entire email list but it shouldn't affect anything, I don't expect people to create MB worth of emails in tests.
I also thought about removing delegating assertions (`assert_email_not_sent` and family) since this is breaking change anyway.
Similar tests were grouped, I think it improves readability a bit.
I would love to hear your thoughts about this one.

Add experimental new test assertion module

---

lib/swoosh/adapters/smtp/helpers.ex
test/swoosh/email/smtp_test.exs

Proposal following [this discussion](https://github.com/swoosh/swoosh/discussions/772).
According to [RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.3) method 1:
> when a message containing a "Bcc:" field is prepared to be sent, the "Bcc:" line is removed even though all of the recipients (including those specified in the "Bcc:" field) are sent a copy of the message
This PR removes the BCC header from the message that is delivered.
Note that the BCC addresses are still included in the `recipients`, so they will still receive the email. It is only the `body` that does not contain the bcc addresses:
https://github.com/swoosh/swoosh/blob/3cab4d812dfef1c842c127e4bb36b475716febe4/lib/swoosh/adapters/smtp.ex#L55-L59

Do not include Bcc header in delivered email

---

README.md

In my project, I want to customise the behaviour of `Swoosh.Mailer`. For example, doing things like:
* Adding custom error handling/reporting
* Chunking delivery of a mail with many recipients into separate mails
* etc...
However, the library makes this difficult, because multiple `deliver` functions are [automatically injected via `use`](https://github.com/swoosh/swoosh/blob/4a59f125c014edaaf9f23de43f76db1e8cb3b691/lib/swoosh/mailer.ex#L125-L155) and are not [overridable](https://hexdocs.pm/elixir/Kernel.html#defoverridable/1). Without being able to override these, the best that can be done is to wrap these functions, however they cannot be replaced so it may be that the default versions can be called accidentally, which I want to avoid (I'd rather replace them with my own versions). …

Remove unnecessary sentence from README

---

CHANGELOG.md

The 1.7.5 version had the subsection levels wrong (h2 instead of h3).
See:

Fix sections on CHANGELOG

---

lib/swoosh/adapters/mailgun.ex

The work is based on this topic: https://elixirforum.com/t/sending-email-404-not-found-nothing-is-happening-no-debug-messages/55230
When using Mailgun sandbox mode you have to set the domain based on the sandbox address used on the API url. Let me know if I should rephrase or move it to somewhere else.
Thanks.

Update Mailgun docs for sandbox mode

---

mix.exs

The documentation code traverses the adapters folder,
so we want to perform it lazily and not every time
mix.exs is loaded.

Compute docs lazily

---

README.md

I am using a CSP in my router and noticed that the mailbox preview was missing all its styling.
I had to adapt my CSP to allow the use of the cdn.

Add a note about the Tailwindcss cdn when using a CSP

---

lib/swoosh/adapters/mailtrap.ex
test/integration/adapters/mailtrap_test.exs
test/swoosh/adapters/mailtrap_test.exs

This PR adds an adapter for Mailtrap Sending and Sandbox APIs.
API docs: https://api-docs.mailtrap.io/docs/mailtrap-api-docs/5tjdeg9545058-mailtrap-api

Implement Mailtrap adapter

---

lib/swoosh/adapters/customer_io.ex
test/swoosh/adapters/customer_io_test.exs

Customer.io transactional emails can have subjects defined in the template, and if the subject is empty they won't deliver the email.
This PR changes the code so that, if the subject is an empty string, it won't set it in the request to customer.io. Previously it would only check if subject is `nil`, but that's not supported by swoosh's API (I still left the `nil` implementation in case someone managed to use it).
Also added a test checking that we're not sending empty `from` values, as those can also be populated by customer.io

Do not send subject to customer.io when empty

---

lib/swoosh/adapters/amazon_ses.ex
test/swoosh/adapters/amazonses_test.exs

The SES API includes a [`Source` parameter](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html) than can be used to specify an email address that SES will use for bounce reports (equivalent to the `MAIL FROM` address when using SMTP).
This PR adds an optional `:ses_source` config option to the `AmazonSES` adapter (and by extension to the the `ExAwsAmazonSES` adapter). Providing the option sets the `Source` field in the API requests to the specified value.
---
Side note: I think it makes sense to have the adapter-specific API fields as options on the adapter, rather than adding them to the email. Even the existing `put_provider_option`s might be better as a adapter options, which can either be configured globally or passed in to `deliver`. Anyway, I need to set …

AmazonSES: add :ses_source option to set Source API parameter

---

lib/swoosh/adapters/mailgun.ex
lib/swoosh/email.ex
test/integration/adapters/mailtrap_test.exs
test/swoosh/adapters/mailgun_test.exs
test/swoosh/adapters/mailtrap_test.exs

feature addition for https://github.com/swoosh/swoosh/issues/849
Added `[mailbox]` to `reply_to` types and handle `is_list` recipients in `emails.ex` and mailgun adapter
now we are getting consistent reply-to

Feat mailgun multiple reply to

---

lib/swoosh/adapters/mandrill.ex
test/swoosh/adapters/mandrill_test.exs

Add support for subaccount and tags as per https://mailchimp.com/developer/transactional/api/messages/send-new-message/ -> message's properties.

Add support of subaccount and tags for Mandrill

---

lib/swoosh/api_client/req.ex
test/swoosh/api_client/req_test.exs

Since Req v0.4.0 (*), request and response headers are _maps_ of name and lists of values, e.g.:
```elixir
%{"content-type" => ["text/html"]}
```
(*) there's a way to keep the old behaviour, setting `config :req, legacy_headers_as_lists: true` but at this point people should upgrade away from it so I wouldn't even worry about it.

Fix Req header handling

---

lib/plug/templates/mailbox_viewer/index.html.eex

Follow up to #822 to make the HTML preview fill the available space and to condense the metadata table at the top so that we get even more space.

Mailbox Preview: more space for the HTML preview

---

lib/swoosh/adapters/mandrill.ex
test/swoosh/adapters/mandrill_test.exs

Mandrill email templates allow specification of the `from` email address and name on the template itself. Swoosh, however, requires `from` to be explicitly set which will cause the template values to always be overridden. This change adds the `allow_nil_from` config option which skips that check and allows use of the template-sourced values.

Add support for allow_nil_from

---

lib/swoosh/adapters/amazon_ses.ex
test/swoosh/adapters/amazonses_test.exs

Implements support for `SourceArn`, `FromArn` and `ReturnPathArn` [request parameters](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html#API_SendRawEmail_RequestParameters) in the AmazonSES adapter. 
These parameters are necessary for scenarios such as sending emails across different AWS accounts where the sender identity is managed in a separate account (which is the use case I'm facing now).
I used this PR as a reference: https://github.com/swoosh/swoosh/pull/846 where the `Source` parameter was set as a config option. Other SES API request parameters `ConfigurationSetName` and `Tags` are passed as provider options. For consistency it might be better to use provider options for all of the request parameters. Maybe that could be another PR if we decide so?

Add config options for AmazonSES adapter

---

lib/swoosh/adapters/mandrill.ex
test/swoosh/adapters/mandrill_test.exs

Add support for tracking_domain and return_path_domain as per  [new message's properties](https://mailchimp.com/developer/transactional/api/messages/send-new-message)

Add support for tracking and return path domains for Mandrill

---

lib/swoosh/adapters/ex_aws_amazon_ses.ex
test/swoosh/adapters/ex_aws_amazonses_test.exs

Fixes issue #913 allowing to override the region set in ex_aws config.

Fix ex_aws region override

---

lib/swoosh/adapters/amazon_ses.ex

Hi there 👋🏼 
I recently ran into the same issue as described in #552 and #578. The solution was to force a recompilation of Swoosh after installing `gen_smtp`. This PR adds a related note to the moduledoc for the adapter.

Explain how to recompile after installing gen_smtp

---

lib/swoosh/mailer.ex

Hi!
I found #939 and decide to check if I could make my first contribution, at least writing docs, so here here it is!
With this PR I write basic documentation for the functions inside the `__using__` `defmacro`:
- `deliver/2`
- `deliver!/2`
- `deliver_many/2`
I know that sometimes functions inside macro are not documented, however, I think it may be useful when the user generates the documentation for its project or even if the user has an editor that shows this docs (at least in my VSCode with ElixirLS in an test project doesn't shows the docs, but I imagine there is some way).
I can't say it fix #939, because I think the issue it is a bit in the wrong direction because `deliver!/2` won't be never in Swoosh documentation because it is implemented outside the `__using__`.
Well, hope this …

Write docs for functions in Mailer __using__ macro 

---

lib/plug/templates/mailbox_viewer/index.html.eex

Text preview can be a bit too much if you're working on debugging or designing emails. This way we have a very easy way to just collapse it out of view.
It would be cool to be able to make it collapsed by default with a configuration flag, but I fist wanted to see what the community thinks of this.

Add toggle for text preview

---

lib/swoosh/adapters/ms_graph.ex

Attempting to resolve #954 
This dependency is more generic than it needs to be _and_ seems to consistently fail in more recent builds as I can't seem to get gen_smtp to return true for Code.ensure_loaded at all, with any variations on how it's specified as a dependency.

Update the MSGraph Adapter Dependency

---

.gitignore
lib/swoosh/adapters/mua.ex
test/swoosh/adapters/mua_test.exs
test/test_helper.exs

Fixes the error reported in https://github.com/swoosh/swoosh/pull/978#issuecomment-2543317353 and adds some basic tests using Mailpit.
And I think it might make sense to retire the Swoosh version with the broken Swoosh.Adapters.Mua:
```console
$ mix hex.retire swoosh 1.17.4 deprecated --message "broken Swoosh.Adapters.Mua"
```
🙏 Sorry for the trouble! 🙏

mua: fix mail.from

---

lib/swoosh/adapters/scaleway.ex

This PR adds the required `type` prop (Scaleways name for "content type") to Scaleway provider.
Any request without "type" fails with 400 error after Scaleway updated their API lately.
Scaleway api docs here: https://www.scaleway.com/en/developers/api/transactional-email/#path-emails-send-an-email

Fix broken attachments on Scaleway adapter

---

README.md
lib/swoosh/adapters/postup.ex
test/swoosh/adapters/postup_test.exs

Similar to https://github.com/swoosh/swoosh/pull/1012, this adapter is somewhat limited in scope but is convenient to implement as I am migrating off of Brevo to PostUp and would like to continue using Swoosh!
This adapter implements [sending a triggered mailing](https://apidocs.postup.com/docs/send-a-triggered-mailing) which can use either template variables or a custom HTML body, title, etc.
Like loops.so, this also has a `from` field that can be ignored, but in this case only if a dummy value is sent instead of a valid email address.

Add PostUp adapter

---

lib/swoosh/adapters/zepto_mail.ex

Currently Zeptomail returns "\n" as body on 500 error, this breaks `Swoosh.json_library().decode!(body)}` since it is not valid json.
The proposed fix tries to decode if possible, or returns the raw body otherwise.

Fix: Prevent zeptomail error when receiving non json response body on 500

---

lib/swoosh/adapters/mua.ex
test/plug/mailbox_preview_test.exs
test/swoosh/adapters/mua_test.exs

I recently migrated a project from using `Swoosh.Adapters.SMTP` to `Swoosh.Adapters.Mua`
and noticed that my inline attachments were no longer working.
Checking the code I saw that the `:type` and `:cid` fields were completely ignored when
creating the `Mail.Attachment`, hence this PR.

Specify the correct content_disposition and content_id

---

lib/plug/templates/mailbox_viewer/index.html.eex

also: set target="_top" inside iframe links to redirect outside of the iframe.
This should provide a lot better dev UX when using the local preview.

make links clickable in text email preview

---

lib/plug/mailbox_preview.ex
test/plug/mailbox_preview_test.exs

This would be super useful for `phx.gen.auth` magic links where we direct folks to `/dev/mailbox` in dev and they can hop to the most recent email for a more convenient login flow in dev

Redirect to latest message in mailbox if one exists

---

test/swoosh/adapters/gmail_test.exs

I noticed there was an unused variable in the gmail test that was raising warnings in CI. 
This should make them go away.

Fix unused variable warnings in CI - Gmail Test

---

lib/swoosh/adapters/sendgrid.ex

Hello team! Recently we started seeing intermittent 406 errors from Sendgrid API. After spending some time researching and talking to their support, we came to a conclusion that a valid Accept header has to be present in all requests. Here is a simple PR to accomplish that. (I'm sorry, had to not follow the general contribution guideline, cuz no request headers covered by the tests. Let me know if you think it makes sense to add such tests though). Here is what we got from their support just in case: 
We're already using this solution in our production and it seems to be working fine.

Add Accept header to all requests made by Sendgrid adapter

---

lib/swoosh/email/render.ex
test/swoosh/adapters/amazonses_test.exs
test/swoosh/email/smtp_test.exs

Hello! I apologize for the unprompted PR.
At work, we are currently investigating switching from Bamboo to Swoosh, and we ran into a specific issue that we thing we can solve.
Some of our users have unconventional names, and we've ran into encoding issues before with SES, in particular with address names.
This PR adds a step in the recipient rendering to escape emails and backslashes to address encoding concerns.
[RFC 5322](https://datatracker.ietf.org/doc/html/rfc5322) defines the following syntax for address names as (with only the relevant bits)
```
name-addr       =   [display-name] angle-addr (Section 3.4)
display-name    =   phrase (Section 3.4)
phrase          =   1*word / obs-phrase (Section 3.2.5)
word            =   atom / quoted-string (Section 3.2.5)
quoted-string   = ... …
```

Escape quotes and backslashes in address names

---

README.md
lib/swoosh/adapters/customer_io.ex
test/swoosh/adapters/customer_io_test.exs

Patterned off of Sendingblue: https://github.com/swoosh/swoosh/issues/537
Also other minor tweaks:
- Add customer.io to the README (is there a defined order? I put it in a rough alphabetical order)
- Fix an errant `"`

Allow Customer.io to use TEMPLATE for from

---

lib/swoosh/email/render.ex
mix.exs
test/swoosh/email/smtp_test.exs

Hello! Sorry once again for an unsolicited PR.
Thank you for working on Swoosh, we just started using it at work, and we ran into a corner case: we have a number of German users who have emails with non-ASCII domain names, such as `_redacted_@hörexperte.de`.
This use case is usually covered by [IDNA](https://en.wikipedia.org/wiki/Internationalized_domain_name) and [RFC 3492](https://datatracker.ietf.org/doc/html/rfc3492), so I thought Swoosh could also handle it. Our previous email setup used the Erlang [`:idna`](https://hexdocs.pm/idna/) package to handle the encoding into Punycode, and since it was already a transitive dependency of hackney, I thought it was a good choice.
The encoding leaves ASCII domains untouched.
Let me know if I can make any changes to improve the PR.

Encode international domain names (IDNA)
